version: '3'
services:
  php:
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    container_name: php
    tty: true
    ports:
      - 80:80
      - 443:443